<%@ page language="java" contentType="text/html; charset=UTF-8" pageEncoding="UTF-8" %>
	<!DOCTYPE html>
	<html lang="ko">

	<head>
		<meta charset="UTF-8">
		<meta name="viewport" content="width=device-width, initial-scale=1.0">
		<title>404 - 불씨를 찾을 수 없어요</title>
		<style>
			@font-face {
				font-family: 'SeoulHangang';
				src: url('https://cdn.jsdelivr.net/gh/projectnoonnu/noonfonts_two@1.0/SeoulHangangM.woff') format('woff');
				font-weight: normal;
				font-display: swap;
			}
		</style>
		<link rel="stylesheet" href="${pageContext.request.contextPath}/css/error/error.css">
	</head>

	<body>

		<!-- Smoke -->
		<div class="smoke-container">
			<div class="smoke"></div>
			<div class="smoke"></div>
			<div class="smoke"></div>
		</div>

		<!-- Floating embers (generated by JS) -->
		<div class="embers" id="embers"></div>

		<!-- Main text -->
		<div class="content">
			<div class="error-number">404</div>
			<div class="title">불씨를 찾을 수 없어요</div>
			<div class="divider"></div>
			<div class="subtitle">
				찾으시는 페이지가 꺼진 모닥불처럼 사라졌어요.<br>
				재가 된 링크일지도 모르니, 주소를 다시 확인해보세요.
			</div>
			<br>
			<a class="btn" href="/main.do">
				<span class="btn-icon">🔥</span>
				홈으로 돌아가기
			</a>
		</div>

		<!-- Campfire -->
		<div class="campfire-wrap">
			<div class="flames">
				<div class="flame flame-outer"></div>
				<div class="flame flame-mid"></div>
				<div class="flame flame-inner"></div>
				<div class="flame flame-core"></div>
			</div>
			<div class="logs">
				<div class="log log-3"></div>
				<div class="log log-1"></div>
				<div class="log log-2"></div>
				<div class="ember-glow"></div>
			</div>
			<div class="stones">
				<div class="stone stone-1"></div>
				<div class="stone stone-2"></div>
				<div class="stone stone-3"></div>
				<div class="stone stone-4"></div>
				<div class="stone stone-5"></div>
			</div>
			<div class="ground-shadow"></div>
		</div>

		<script>
			const emberContainer = document.getElementById('embers');
			const emberColors = [
				'rgba(255,120,20,0.9)',
				'rgba(255,80,0,0.85)',
				'rgba(255,180,30,0.8)',
				'rgba(220,60,0,0.75)',
				'rgba(255,140,40,0.7)',
			];

			function createEmber() {
				const el = document.createElement('div');
				el.className = 'ember';
				const size = Math.random() * 4 + 1.5;
				const left = Math.random() * 160 + 70;
				const duration = Math.random() * 3 + 2.5;
				const delay = Math.random() * 3;
				const dx = (Math.random() - 0.5) * 120;
				const color = emberColors[Math.floor(Math.random() * emberColors.length)];

				el.style.cssText = `
      width:${size}px; height:${size}px;
      left:${left}px; bottom:0;
      background:${color};
      box-shadow: 0 0 ${size * 2}px ${color};
      --dx:${dx}px;
      animation-duration:${duration}s;
      animation-delay:${delay}s;
    `;
				emberContainer.appendChild(el);
				setTimeout(() => el.remove(), (duration + delay) * 1000);
			}

			setInterval(createEmber, 220);
			for (let i = 0; i < 12; i++) setTimeout(createEmber, i * 180);

			// Ash particles
			const ashDxValues = [-60, -30, 40, 20, -50, 55, -15, 35];
			ashDxValues.forEach((ax, i) => {
				const ash = document.createElement('div');
				ash.className = 'ash';
				ash.style.cssText = `
      left:${44 + Math.random() * 12}%;
      bottom:${120 + Math.random() * 60}px;
      --ax:${ax}px;
      animation-duration:${7 + i * 0.8}s;
      animation-delay:${i * 1.1}s;
      width:${Math.random() * 2 + 2}px;
      height:${Math.random() * 2 + 2}px;
    `;
				document.body.appendChild(ash);
			});
		</script>
	</body>

	</html>

	<script>
		const app = Vue.createApp({
			data() {
				return {
					message: ""
				};
			},
			methods: {
				fnError: function () {
					let self = this;
					$.ajax({
						url: "http://localhost:8080/error.dox",
						dataType: "json",
						type: "POST",
						data: {}, // Sending empty object if no params needed
						success: function (data) {
							console.log("Server Response:", data);
							self.message = data.message;
						},
						error: function (err) {
							console.error("AJAX Error:", err);
						}
					});
				}
			},
			mounted() {
				this.fnError();
			}
		});
		app.mount('#app');
	</script>